# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e645fd6b070ec784193dac1f1c06034f961c0f4cddfa7a43a38ebebf4d9b78bbdf3352699c39ca91b141860127f2f9c27ec25427e2e2ea802d04e6c80e6e5c1c

test:
  secret_key_base: 9e49ebbd3823e55b8b97a08cf7149c86a0e70e4093a01b97025d084d7e0534af5d935c58f80b1cdaec237562a9dd4b0d8448f068f122e897b90177e2871cde46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
